### ISSUE TITLE
A Few Possible Corrections

### ISSUE THREAD

**Issue by ng-chicago** [cfjedimaster/eleventy-blog-guide#3]
Great article, thanks!  
A few possible things to correct.  

You can see the shortcode, `except` in use after the title and date.  
s/b `excerpt` not except?  

Our posts all contain a categories `from` matter.  
s/b `front` not from?  

Now we need to add the feed page itself.  
Suggested new file name is not there - s/b  feed.njk ?  

add a new layout named `posts.liquid`:  
The matching code under that s/b `posts` not post?  
```json  
{  
	"layout":"post"  
}  
```

**Comment by cfjedimaster** [comment]
Thank you! Fixed and HTML updated.
